outfile: count.o add.o main.o print.o
	cc  count.o add.o main.o print.o -o outfile
count.o:count.c
	cc -c count.c
add.o:add.c
	cc -c add.c
main.o:main.c
	cc -c main.c
print.o:print.c
	cc -c print.c


